ERROR - 2022-11-09 22:17:48 --> Error connecting to the database: mysqli_sql_exception: La dirección solicitada no es válida en este contexto.
 in C:\laragon\www\api.denver\system\Database\MySQLi\Connection.php:171
Stack trace:
#0 C:\laragon\www\api.denver\system\Database\MySQLi\Connection.php(171): mysqli->real_connect('https://curricu...', 'id19841826_spoo...', '@NJX<{xmzo&gz%1...', 'id19841826_denv...', 3306, '', 0)
#1 C:\laragon\www\api.denver\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\laragon\www\api.denver\system\Database\BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\laragon\www\api.denver\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\laragon\www\api.denver\system\Model.php(223): CodeIgniter\Database\BaseBuilder->get()
#5 C:\laragon\www\api.denver\system\BaseModel.php(585): CodeIgniter\Model->doFindAll(0, 0)
#6 C:\laragon\www\api.denver\app\Controllers\Actividad.php(12): CodeIgniter\BaseModel->findAll()
#7 C:\laragon\www\api.denver\system\CodeIgniter.php(927): App\Controllers\Actividad->index()
#8 C:\laragon\www\api.denver\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Actividad))
#9 C:\laragon\www\api.denver\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\laragon\www\api.denver\public\index.php(67): CodeIgniter\CodeIgniter->run()
#11 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: La dirección solicitada no es válida en este contexto.
 in C:\laragon\www\api.denver\system\Database\MySQLi\Connection.php:215
Stack trace:
#0 C:\laragon\www\api.denver\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\laragon\www\api.denver\system\Database\BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\laragon\www\api.denver\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\laragon\www\api.denver\system\Model.php(223): CodeIgniter\Database\BaseBuilder->get()
#4 C:\laragon\www\api.denver\system\BaseModel.php(585): CodeIgniter\Model->doFindAll(0, 0)
#5 C:\laragon\www\api.denver\app\Controllers\Actividad.php(12): CodeIgniter\BaseModel->findAll()
#6 C:\laragon\www\api.denver\system\CodeIgniter.php(927): App\Controllers\Actividad->index()
#7 C:\laragon\www\api.denver\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Actividad))
#8 C:\laragon\www\api.denver\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\laragon\www\api.denver\public\index.php(67): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2022-11-09 22:17:48 --> Unable to connect to the database.
Main connection [MySQLi]: La dirección solicitada no es válida en este contexto.

in SYSTEMPATH\Database\BaseConnection.php on line 418.
 1 SYSTEMPATH\Database\BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `actividad`', [], false)
 3 SYSTEMPATH\Model.php(223): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(585): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Controllers\Actividad.php(12): CodeIgniter\BaseModel->findAll()
 6 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\Actividad->index()
 7 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Actividad))
 8 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2022-11-09 22:58:25 --> Error connecting to the database: mysqli_sql_exception: No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión.
 in C:\laragon\www\api.denver\system\Database\MySQLi\Connection.php:171
Stack trace:
#0 C:\laragon\www\api.denver\system\Database\MySQLi\Connection.php(171): mysqli->real_connect('files.000webhos...', 'id19841826_spoo...', '@NJX<{xmzo&gz%1...', 'id19841826_denv...', 3306, '', 0)
#1 C:\laragon\www\api.denver\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\laragon\www\api.denver\system\Database\BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\laragon\www\api.denver\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\laragon\www\api.denver\system\Model.php(223): CodeIgniter\Database\BaseBuilder->get()
#5 C:\laragon\www\api.denver\system\BaseModel.php(585): CodeIgniter\Model->doFindAll(0, 0)
#6 C:\laragon\www\api.denver\app\Controllers\Actividad.php(12): CodeIgniter\BaseModel->findAll()
#7 C:\laragon\www\api.denver\system\CodeIgniter.php(927): App\Controllers\Actividad->index()
#8 C:\laragon\www\api.denver\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Actividad))
#9 C:\laragon\www\api.denver\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\laragon\www\api.denver\public\index.php(67): CodeIgniter\CodeIgniter->run()
#11 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión.
 in C:\laragon\www\api.denver\system\Database\MySQLi\Connection.php:215
Stack trace:
#0 C:\laragon\www\api.denver\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\laragon\www\api.denver\system\Database\BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\laragon\www\api.denver\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\laragon\www\api.denver\system\Model.php(223): CodeIgniter\Database\BaseBuilder->get()
#4 C:\laragon\www\api.denver\system\BaseModel.php(585): CodeIgniter\Model->doFindAll(0, 0)
#5 C:\laragon\www\api.denver\app\Controllers\Actividad.php(12): CodeIgniter\BaseModel->findAll()
#6 C:\laragon\www\api.denver\system\CodeIgniter.php(927): App\Controllers\Actividad->index()
#7 C:\laragon\www\api.denver\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Actividad))
#8 C:\laragon\www\api.denver\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\laragon\www\api.denver\public\index.php(67): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2022-11-09 22:58:25 --> Unable to connect to the database.
Main connection [MySQLi]: No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión.

in SYSTEMPATH\Database\BaseConnection.php on line 418.
 1 SYSTEMPATH\Database\BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `actividad`', [], false)
 3 SYSTEMPATH\Model.php(223): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(585): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Controllers\Actividad.php(12): CodeIgniter\BaseModel->findAll()
 6 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\Actividad->index()
 7 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Actividad))
 8 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2022-11-09 23:33:34 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'u534750869_spoonme'@'2806:1016:8:8668:11ab:998c:8333:4214' (using password: YES) in C:\laragon\www\api.denver\system\Database\MySQLi\Connection.php:171
Stack trace:
#0 C:\laragon\www\api.denver\system\Database\MySQLi\Connection.php(171): mysqli->real_connect('denvermx.online', 'u534750869_spoo...', 'Spoonme876', 'u534750869_denv...', 3306, '', 0)
#1 C:\laragon\www\api.denver\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\laragon\www\api.denver\system\Database\BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\laragon\www\api.denver\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\laragon\www\api.denver\system\Model.php(223): CodeIgniter\Database\BaseBuilder->get()
#5 C:\laragon\www\api.denver\system\BaseModel.php(585): CodeIgniter\Model->doFindAll(0, 0)
#6 C:\laragon\www\api.denver\app\Controllers\Actividad.php(12): CodeIgniter\BaseModel->findAll()
#7 C:\laragon\www\api.denver\system\CodeIgniter.php(927): App\Controllers\Actividad->index()
#8 C:\laragon\www\api.denver\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Actividad))
#9 C:\laragon\www\api.denver\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\laragon\www\api.denver\public\index.php(67): CodeIgniter\CodeIgniter->run()
#11 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'2806:1016:8:8668:11ab:998c:8333:4214' (using password: YES) in C:\laragon\www\api.denver\system\Database\MySQLi\Connection.php:215
Stack trace:
#0 C:\laragon\www\api.denver\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\laragon\www\api.denver\system\Database\BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\laragon\www\api.denver\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\laragon\www\api.denver\system\Model.php(223): CodeIgniter\Database\BaseBuilder->get()
#4 C:\laragon\www\api.denver\system\BaseModel.php(585): CodeIgniter\Model->doFindAll(0, 0)
#5 C:\laragon\www\api.denver\app\Controllers\Actividad.php(12): CodeIgniter\BaseModel->findAll()
#6 C:\laragon\www\api.denver\system\CodeIgniter.php(927): App\Controllers\Actividad->index()
#7 C:\laragon\www\api.denver\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Actividad))
#8 C:\laragon\www\api.denver\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\laragon\www\api.denver\public\index.php(67): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2022-11-09 23:33:34 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'2806:1016:8:8668:11ab:998c:8333:4214' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 418.
 1 SYSTEMPATH\Database\BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `actividad`', [], false)
 3 SYSTEMPATH\Model.php(223): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(585): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Controllers\Actividad.php(12): CodeIgniter\BaseModel->findAll()
 6 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\Actividad->index()
 7 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Actividad))
 8 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2022-11-09 23:33:39 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'u534750869_spoonme'@'2806:1016:8:8668:11ab:998c:8333:4214' (using password: YES) in C:\laragon\www\api.denver\system\Database\MySQLi\Connection.php:171
Stack trace:
#0 C:\laragon\www\api.denver\system\Database\MySQLi\Connection.php(171): mysqli->real_connect('denvermx.online', 'u534750869_spoo...', 'Spoonme876', 'u534750869_denv...', 3306, '', 0)
#1 C:\laragon\www\api.denver\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\laragon\www\api.denver\system\Database\BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\laragon\www\api.denver\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\laragon\www\api.denver\system\Model.php(223): CodeIgniter\Database\BaseBuilder->get()
#5 C:\laragon\www\api.denver\system\BaseModel.php(585): CodeIgniter\Model->doFindAll(0, 0)
#6 C:\laragon\www\api.denver\app\Controllers\Actividad.php(12): CodeIgniter\BaseModel->findAll()
#7 C:\laragon\www\api.denver\system\CodeIgniter.php(927): App\Controllers\Actividad->index()
#8 C:\laragon\www\api.denver\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Actividad))
#9 C:\laragon\www\api.denver\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\laragon\www\api.denver\public\index.php(67): CodeIgniter\CodeIgniter->run()
#11 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'2806:1016:8:8668:11ab:998c:8333:4214' (using password: YES) in C:\laragon\www\api.denver\system\Database\MySQLi\Connection.php:215
Stack trace:
#0 C:\laragon\www\api.denver\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\laragon\www\api.denver\system\Database\BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\laragon\www\api.denver\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\laragon\www\api.denver\system\Model.php(223): CodeIgniter\Database\BaseBuilder->get()
#4 C:\laragon\www\api.denver\system\BaseModel.php(585): CodeIgniter\Model->doFindAll(0, 0)
#5 C:\laragon\www\api.denver\app\Controllers\Actividad.php(12): CodeIgniter\BaseModel->findAll()
#6 C:\laragon\www\api.denver\system\CodeIgniter.php(927): App\Controllers\Actividad->index()
#7 C:\laragon\www\api.denver\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Actividad))
#8 C:\laragon\www\api.denver\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\laragon\www\api.denver\public\index.php(67): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2022-11-09 23:33:39 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'2806:1016:8:8668:11ab:998c:8333:4214' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 418.
 1 SYSTEMPATH\Database\BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `actividad`', [], false)
 3 SYSTEMPATH\Model.php(223): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(585): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Controllers\Actividad.php(12): CodeIgniter\BaseModel->findAll()
 6 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\Actividad->index()
 7 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Actividad))
 8 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2022-11-09 23:34:28 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'u534750869_spoonme'@'2806:1016:8:8668:11ab:998c:8333:4214' (using password: YES) in C:\laragon\www\api.denver\system\Database\MySQLi\Connection.php:171
Stack trace:
#0 C:\laragon\www\api.denver\system\Database\MySQLi\Connection.php(171): mysqli->real_connect('denvermx.online', 'u534750869_spoo...', 'Spoonme876', 'u534750869_denv...', 3306, '', 0)
#1 C:\laragon\www\api.denver\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\laragon\www\api.denver\system\Database\BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\laragon\www\api.denver\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\laragon\www\api.denver\system\Model.php(223): CodeIgniter\Database\BaseBuilder->get()
#5 C:\laragon\www\api.denver\system\BaseModel.php(585): CodeIgniter\Model->doFindAll(0, 0)
#6 C:\laragon\www\api.denver\app\Controllers\Actividad.php(12): CodeIgniter\BaseModel->findAll()
#7 C:\laragon\www\api.denver\system\CodeIgniter.php(927): App\Controllers\Actividad->index()
#8 C:\laragon\www\api.denver\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Actividad))
#9 C:\laragon\www\api.denver\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\laragon\www\api.denver\public\index.php(67): CodeIgniter\CodeIgniter->run()
#11 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'2806:1016:8:8668:11ab:998c:8333:4214' (using password: YES) in C:\laragon\www\api.denver\system\Database\MySQLi\Connection.php:215
Stack trace:
#0 C:\laragon\www\api.denver\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\laragon\www\api.denver\system\Database\BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\laragon\www\api.denver\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\laragon\www\api.denver\system\Model.php(223): CodeIgniter\Database\BaseBuilder->get()
#4 C:\laragon\www\api.denver\system\BaseModel.php(585): CodeIgniter\Model->doFindAll(0, 0)
#5 C:\laragon\www\api.denver\app\Controllers\Actividad.php(12): CodeIgniter\BaseModel->findAll()
#6 C:\laragon\www\api.denver\system\CodeIgniter.php(927): App\Controllers\Actividad->index()
#7 C:\laragon\www\api.denver\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Actividad))
#8 C:\laragon\www\api.denver\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\laragon\www\api.denver\public\index.php(67): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2022-11-09 23:34:28 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'2806:1016:8:8668:11ab:998c:8333:4214' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 418.
 1 SYSTEMPATH\Database\BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `actividad`', [], false)
 3 SYSTEMPATH\Model.php(223): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(585): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Controllers\Actividad.php(12): CodeIgniter\BaseModel->findAll()
 6 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\Actividad->index()
 7 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Actividad))
 8 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2022-11-09 23:35:05 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'u534750869_spoonme'@'2806:1016:8:8668:11ab:998c:8333:4214' (using password: YES) in C:\laragon\www\api.denver\system\Database\MySQLi\Connection.php:171
Stack trace:
#0 C:\laragon\www\api.denver\system\Database\MySQLi\Connection.php(171): mysqli->real_connect('denvermx.online', 'u534750869_spoo...', 'Spoonme876', 'u534750869_denv...', 3306, '', 0)
#1 C:\laragon\www\api.denver\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\laragon\www\api.denver\system\Database\BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\laragon\www\api.denver\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\laragon\www\api.denver\system\Model.php(223): CodeIgniter\Database\BaseBuilder->get()
#5 C:\laragon\www\api.denver\system\BaseModel.php(585): CodeIgniter\Model->doFindAll(0, 0)
#6 C:\laragon\www\api.denver\app\Controllers\Actividad.php(12): CodeIgniter\BaseModel->findAll()
#7 C:\laragon\www\api.denver\system\CodeIgniter.php(927): App\Controllers\Actividad->index()
#8 C:\laragon\www\api.denver\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Actividad))
#9 C:\laragon\www\api.denver\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\laragon\www\api.denver\public\index.php(67): CodeIgniter\CodeIgniter->run()
#11 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'2806:1016:8:8668:11ab:998c:8333:4214' (using password: YES) in C:\laragon\www\api.denver\system\Database\MySQLi\Connection.php:215
Stack trace:
#0 C:\laragon\www\api.denver\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\laragon\www\api.denver\system\Database\BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\laragon\www\api.denver\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\laragon\www\api.denver\system\Model.php(223): CodeIgniter\Database\BaseBuilder->get()
#4 C:\laragon\www\api.denver\system\BaseModel.php(585): CodeIgniter\Model->doFindAll(0, 0)
#5 C:\laragon\www\api.denver\app\Controllers\Actividad.php(12): CodeIgniter\BaseModel->findAll()
#6 C:\laragon\www\api.denver\system\CodeIgniter.php(927): App\Controllers\Actividad->index()
#7 C:\laragon\www\api.denver\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Actividad))
#8 C:\laragon\www\api.denver\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\laragon\www\api.denver\public\index.php(67): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2022-11-09 23:35:05 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'2806:1016:8:8668:11ab:998c:8333:4214' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 418.
 1 SYSTEMPATH\Database\BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `actividad`', [], false)
 3 SYSTEMPATH\Model.php(223): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(585): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Controllers\Actividad.php(12): CodeIgniter\BaseModel->findAll()
 6 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\Actividad->index()
 7 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Actividad))
 8 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2022-11-09 23:35:30 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'u534750869_spoonme'@'2806:1016:8:8668:11ab:998c:8333:4214' (using password: YES) in C:\laragon\www\api.denver\system\Database\MySQLi\Connection.php:171
Stack trace:
#0 C:\laragon\www\api.denver\system\Database\MySQLi\Connection.php(171): mysqli->real_connect('denvermx.online', 'u534750869_spoo...', 'Spoonme876', 'u534750869_denv...', 3306, '', 0)
#1 C:\laragon\www\api.denver\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\laragon\www\api.denver\system\Database\BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\laragon\www\api.denver\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\laragon\www\api.denver\system\Model.php(223): CodeIgniter\Database\BaseBuilder->get()
#5 C:\laragon\www\api.denver\system\BaseModel.php(585): CodeIgniter\Model->doFindAll(0, 0)
#6 C:\laragon\www\api.denver\app\Controllers\Actividad.php(12): CodeIgniter\BaseModel->findAll()
#7 C:\laragon\www\api.denver\system\CodeIgniter.php(927): App\Controllers\Actividad->index()
#8 C:\laragon\www\api.denver\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Actividad))
#9 C:\laragon\www\api.denver\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\laragon\www\api.denver\public\index.php(67): CodeIgniter\CodeIgniter->run()
#11 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'2806:1016:8:8668:11ab:998c:8333:4214' (using password: YES) in C:\laragon\www\api.denver\system\Database\MySQLi\Connection.php:215
Stack trace:
#0 C:\laragon\www\api.denver\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\laragon\www\api.denver\system\Database\BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\laragon\www\api.denver\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\laragon\www\api.denver\system\Model.php(223): CodeIgniter\Database\BaseBuilder->get()
#4 C:\laragon\www\api.denver\system\BaseModel.php(585): CodeIgniter\Model->doFindAll(0, 0)
#5 C:\laragon\www\api.denver\app\Controllers\Actividad.php(12): CodeIgniter\BaseModel->findAll()
#6 C:\laragon\www\api.denver\system\CodeIgniter.php(927): App\Controllers\Actividad->index()
#7 C:\laragon\www\api.denver\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Actividad))
#8 C:\laragon\www\api.denver\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\laragon\www\api.denver\public\index.php(67): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2022-11-09 23:35:30 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'2806:1016:8:8668:11ab:998c:8333:4214' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 418.
 1 SYSTEMPATH\Database\BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `actividad`', [], false)
 3 SYSTEMPATH\Model.php(223): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(585): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Controllers\Actividad.php(12): CodeIgniter\BaseModel->findAll()
 6 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\Actividad->index()
 7 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Actividad))
 8 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2022-11-09 23:35:45 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'u534750869_spoonme'@'2806:1016:8:8668:11ab:998c:8333:4214' (using password: YES) in C:\laragon\www\api.denver\system\Database\MySQLi\Connection.php:171
Stack trace:
#0 C:\laragon\www\api.denver\system\Database\MySQLi\Connection.php(171): mysqli->real_connect('denvermx.online', 'u534750869_spoo...', 'Spoonme876', 'u534750869_denv...', 3306, '', 0)
#1 C:\laragon\www\api.denver\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\laragon\www\api.denver\system\Database\BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\laragon\www\api.denver\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\laragon\www\api.denver\system\Model.php(223): CodeIgniter\Database\BaseBuilder->get()
#5 C:\laragon\www\api.denver\system\BaseModel.php(585): CodeIgniter\Model->doFindAll(0, 0)
#6 C:\laragon\www\api.denver\app\Controllers\Terapeuta.php(14): CodeIgniter\BaseModel->findAll()
#7 C:\laragon\www\api.denver\system\CodeIgniter.php(927): App\Controllers\Terapeuta->index()
#8 C:\laragon\www\api.denver\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Terapeuta))
#9 C:\laragon\www\api.denver\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\laragon\www\api.denver\public\index.php(67): CodeIgniter\CodeIgniter->run()
#11 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'2806:1016:8:8668:11ab:998c:8333:4214' (using password: YES) in C:\laragon\www\api.denver\system\Database\MySQLi\Connection.php:215
Stack trace:
#0 C:\laragon\www\api.denver\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\laragon\www\api.denver\system\Database\BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\laragon\www\api.denver\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\laragon\www\api.denver\system\Model.php(223): CodeIgniter\Database\BaseBuilder->get()
#4 C:\laragon\www\api.denver\system\BaseModel.php(585): CodeIgniter\Model->doFindAll(0, 0)
#5 C:\laragon\www\api.denver\app\Controllers\Terapeuta.php(14): CodeIgniter\BaseModel->findAll()
#6 C:\laragon\www\api.denver\system\CodeIgniter.php(927): App\Controllers\Terapeuta->index()
#7 C:\laragon\www\api.denver\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Terapeuta))
#8 C:\laragon\www\api.denver\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\laragon\www\api.denver\public\index.php(67): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2022-11-09 23:35:45 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'2806:1016:8:8668:11ab:998c:8333:4214' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 418.
 1 SYSTEMPATH\Database\BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `terapeutas`', [], false)
 3 SYSTEMPATH\Model.php(223): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(585): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Controllers\Terapeuta.php(14): CodeIgniter\BaseModel->findAll()
 6 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\Terapeuta->index()
 7 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Terapeuta))
 8 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2022-11-09 23:37:21 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'u534750869_spoonme'@'2806:1016:8:8668:11ab:998c:8333:4214' (using password: YES) in C:\laragon\www\api.denver\system\Database\MySQLi\Connection.php:171
Stack trace:
#0 C:\laragon\www\api.denver\system\Database\MySQLi\Connection.php(171): mysqli->real_connect('denvermx.online', 'u534750869_spoo...', 'Jesus876', 'u534750869_denv...', 3306, '', 0)
#1 C:\laragon\www\api.denver\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\laragon\www\api.denver\system\Database\BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\laragon\www\api.denver\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\laragon\www\api.denver\system\Model.php(223): CodeIgniter\Database\BaseBuilder->get()
#5 C:\laragon\www\api.denver\system\BaseModel.php(585): CodeIgniter\Model->doFindAll(0, 0)
#6 C:\laragon\www\api.denver\app\Controllers\Terapeuta.php(14): CodeIgniter\BaseModel->findAll()
#7 C:\laragon\www\api.denver\system\CodeIgniter.php(927): App\Controllers\Terapeuta->index()
#8 C:\laragon\www\api.denver\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Terapeuta))
#9 C:\laragon\www\api.denver\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\laragon\www\api.denver\public\index.php(67): CodeIgniter\CodeIgniter->run()
#11 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'2806:1016:8:8668:11ab:998c:8333:4214' (using password: YES) in C:\laragon\www\api.denver\system\Database\MySQLi\Connection.php:215
Stack trace:
#0 C:\laragon\www\api.denver\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\laragon\www\api.denver\system\Database\BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\laragon\www\api.denver\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\laragon\www\api.denver\system\Model.php(223): CodeIgniter\Database\BaseBuilder->get()
#4 C:\laragon\www\api.denver\system\BaseModel.php(585): CodeIgniter\Model->doFindAll(0, 0)
#5 C:\laragon\www\api.denver\app\Controllers\Terapeuta.php(14): CodeIgniter\BaseModel->findAll()
#6 C:\laragon\www\api.denver\system\CodeIgniter.php(927): App\Controllers\Terapeuta->index()
#7 C:\laragon\www\api.denver\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Terapeuta))
#8 C:\laragon\www\api.denver\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\laragon\www\api.denver\public\index.php(67): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2022-11-09 23:37:21 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'2806:1016:8:8668:11ab:998c:8333:4214' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 418.
 1 SYSTEMPATH\Database\BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `terapeutas`', [], false)
 3 SYSTEMPATH\Model.php(223): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(585): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Controllers\Terapeuta.php(14): CodeIgniter\BaseModel->findAll()
 6 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\Terapeuta->index()
 7 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Terapeuta))
 8 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
