ERROR - 2022-11-10 12:43:17 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'u534750869_spoonme'@'2806:1016:8:8668:11ab:998c:8333:4214' (using password: YES) in C:\laragon\www\api.denver\system\Database\MySQLi\Connection.php:171
Stack trace:
#0 C:\laragon\www\api.denver\system\Database\MySQLi\Connection.php(171): mysqli->real_connect('denvermx.online', 'u534750869_spoo...', 'Jesus876', 'u534750869_denv...', 3306, '', 0)
#1 C:\laragon\www\api.denver\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\laragon\www\api.denver\system\Database\BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\laragon\www\api.denver\system\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `ac...', Array, false)
#4 C:\laragon\www\api.denver\system\Model.php(279): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\laragon\www\api.denver\system\BaseModel.php(749): CodeIgniter\Model->doInsert(Array)
#6 C:\laragon\www\api.denver\system\Model.php(667): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\laragon\www\api.denver\app\Controllers\Actividad.php(55): CodeIgniter\Model->insert(Array)
#8 C:\laragon\www\api.denver\system\CodeIgniter.php(927): App\Controllers\Actividad->create()
#9 C:\laragon\www\api.denver\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Actividad))
#10 C:\laragon\www\api.denver\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\laragon\www\api.denver\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'2806:1016:8:8668:11ab:998c:8333:4214' (using password: YES) in C:\laragon\www\api.denver\system\Database\MySQLi\Connection.php:215
Stack trace:
#0 C:\laragon\www\api.denver\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\laragon\www\api.denver\system\Database\BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\laragon\www\api.denver\system\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `ac...', Array, false)
#3 C:\laragon\www\api.denver\system\Model.php(279): CodeIgniter\Database\BaseBuilder->insert()
#4 C:\laragon\www\api.denver\system\BaseModel.php(749): CodeIgniter\Model->doInsert(Array)
#5 C:\laragon\www\api.denver\system\Model.php(667): CodeIgniter\BaseModel->insert(Array, true)
#6 C:\laragon\www\api.denver\app\Controllers\Actividad.php(55): CodeIgniter\Model->insert(Array)
#7 C:\laragon\www\api.denver\system\CodeIgniter.php(927): App\Controllers\Actividad->create()
#8 C:\laragon\www\api.denver\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Actividad))
#9 C:\laragon\www\api.denver\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\laragon\www\api.denver\public\index.php(67): CodeIgniter\CodeIgniter->run()
#11 {main}
CRITICAL - 2022-11-10 12:43:17 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'2806:1016:8:8668:11ab:998c:8333:4214' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 418.
 1 SYSTEMPATH\Database\BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `actividad` (`nombre`, `descripcion`, `idTopico`, `ejemplo`) VALUES (:nombre:, :descripcion:, :idTopico:, :ejemplo:)', [...], false)
 3 SYSTEMPATH\Model.php(279): CodeIgniter\Database\BaseBuilder->insert()
 4 SYSTEMPATH\BaseModel.php(749): CodeIgniter\Model->doInsert([...])
 5 SYSTEMPATH\Model.php(667): CodeIgniter\BaseModel->insert([...], true)
 6 APPPATH\Controllers\Actividad.php(55): CodeIgniter\Model->insert([...])
 7 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\Actividad->create()
 8 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Actividad))
 9 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2022-11-10 13:23:11 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'u534750869_spoonme'@'2806:1016:8:8668:11ab:998c:8333:4214' (using password: YES) in C:\laragon\www\api.denver\system\Database\MySQLi\Connection.php:171
Stack trace:
#0 C:\laragon\www\api.denver\system\Database\MySQLi\Connection.php(171): mysqli->real_connect('denvermx.online', 'u534750869_spoo...', 'Jesus876', 'u534750869_denv...', 3306, '', 0)
#1 C:\laragon\www\api.denver\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\laragon\www\api.denver\system\Database\BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\laragon\www\api.denver\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\laragon\www\api.denver\system\Model.php(250): CodeIgniter\Database\BaseBuilder->get()
#5 C:\laragon\www\api.denver\system\BaseModel.php(623): CodeIgniter\Model->doFirst()
#6 C:\laragon\www\api.denver\app\Models\PadreModel.php(22): CodeIgniter\BaseModel->first()
#7 C:\laragon\www\api.denver\app\Controllers\Padre.php(114): App\Models\PadreModel->login('jose@gmail.com', 'jose')
#8 C:\laragon\www\api.denver\system\CodeIgniter.php(927): App\Controllers\Padre->login()
#9 C:\laragon\www\api.denver\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Padre))
#10 C:\laragon\www\api.denver\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\laragon\www\api.denver\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'2806:1016:8:8668:11ab:998c:8333:4214' (using password: YES) in C:\laragon\www\api.denver\system\Database\MySQLi\Connection.php:215
Stack trace:
#0 C:\laragon\www\api.denver\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\laragon\www\api.denver\system\Database\BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\laragon\www\api.denver\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\laragon\www\api.denver\system\Model.php(250): CodeIgniter\Database\BaseBuilder->get()
#4 C:\laragon\www\api.denver\system\BaseModel.php(623): CodeIgniter\Model->doFirst()
#5 C:\laragon\www\api.denver\app\Models\PadreModel.php(22): CodeIgniter\BaseModel->first()
#6 C:\laragon\www\api.denver\app\Controllers\Padre.php(114): App\Models\PadreModel->login('jose@gmail.com', 'jose')
#7 C:\laragon\www\api.denver\system\CodeIgniter.php(927): App\Controllers\Padre->login()
#8 C:\laragon\www\api.denver\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Padre))
#9 C:\laragon\www\api.denver\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\laragon\www\api.denver\public\index.php(67): CodeIgniter\CodeIgniter->run()
#11 {main}
CRITICAL - 2022-11-10 13:23:11 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'2806:1016:8:8668:11ab:998c:8333:4214' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 418.
 1 SYSTEMPATH\Database\BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `padres`
WHERE `correo` = :correo:
AND `pass` = :pass:
 LIMIT 1', [...], false)
 3 SYSTEMPATH\Model.php(250): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(623): CodeIgniter\Model->doFirst()
 5 APPPATH\Models\PadreModel.php(22): CodeIgniter\BaseModel->first()
 6 APPPATH\Controllers\Padre.php(114): App\Models\PadreModel->login('jose@gmail.com', 'jose')
 7 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\Padre->login()
 8 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Padre))
 9 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2022-11-10 13:23:13 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'u534750869_spoonme'@'2806:1016:8:8668:11ab:998c:8333:4214' (using password: YES) in C:\laragon\www\api.denver\system\Database\MySQLi\Connection.php:171
Stack trace:
#0 C:\laragon\www\api.denver\system\Database\MySQLi\Connection.php(171): mysqli->real_connect('denvermx.online', 'u534750869_spoo...', 'Jesus876', 'u534750869_denv...', 3306, '', 0)
#1 C:\laragon\www\api.denver\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\laragon\www\api.denver\system\Database\BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\laragon\www\api.denver\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\laragon\www\api.denver\system\Model.php(250): CodeIgniter\Database\BaseBuilder->get()
#5 C:\laragon\www\api.denver\system\BaseModel.php(623): CodeIgniter\Model->doFirst()
#6 C:\laragon\www\api.denver\app\Models\PadreModel.php(22): CodeIgniter\BaseModel->first()
#7 C:\laragon\www\api.denver\app\Controllers\Padre.php(114): App\Models\PadreModel->login('jose@gmail.com', 'jose')
#8 C:\laragon\www\api.denver\system\CodeIgniter.php(927): App\Controllers\Padre->login()
#9 C:\laragon\www\api.denver\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Padre))
#10 C:\laragon\www\api.denver\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\laragon\www\api.denver\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'2806:1016:8:8668:11ab:998c:8333:4214' (using password: YES) in C:\laragon\www\api.denver\system\Database\MySQLi\Connection.php:215
Stack trace:
#0 C:\laragon\www\api.denver\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\laragon\www\api.denver\system\Database\BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\laragon\www\api.denver\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\laragon\www\api.denver\system\Model.php(250): CodeIgniter\Database\BaseBuilder->get()
#4 C:\laragon\www\api.denver\system\BaseModel.php(623): CodeIgniter\Model->doFirst()
#5 C:\laragon\www\api.denver\app\Models\PadreModel.php(22): CodeIgniter\BaseModel->first()
#6 C:\laragon\www\api.denver\app\Controllers\Padre.php(114): App\Models\PadreModel->login('jose@gmail.com', 'jose')
#7 C:\laragon\www\api.denver\system\CodeIgniter.php(927): App\Controllers\Padre->login()
#8 C:\laragon\www\api.denver\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Padre))
#9 C:\laragon\www\api.denver\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\laragon\www\api.denver\public\index.php(67): CodeIgniter\CodeIgniter->run()
#11 {main}
CRITICAL - 2022-11-10 13:23:13 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'2806:1016:8:8668:11ab:998c:8333:4214' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 418.
 1 SYSTEMPATH\Database\BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `padres`
WHERE `correo` = :correo:
AND `pass` = :pass:
 LIMIT 1', [...], false)
 3 SYSTEMPATH\Model.php(250): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(623): CodeIgniter\Model->doFirst()
 5 APPPATH\Models\PadreModel.php(22): CodeIgniter\BaseModel->first()
 6 APPPATH\Controllers\Padre.php(114): App\Models\PadreModel->login('jose@gmail.com', 'jose')
 7 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\Padre->login()
 8 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Padre))
 9 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2022-11-10 13:23:16 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'u534750869_spoonme'@'2806:1016:8:8668:11ab:998c:8333:4214' (using password: YES) in C:\laragon\www\api.denver\system\Database\MySQLi\Connection.php:171
Stack trace:
#0 C:\laragon\www\api.denver\system\Database\MySQLi\Connection.php(171): mysqli->real_connect('denvermx.online', 'u534750869_spoo...', 'Jesus876', 'u534750869_denv...', 3306, '', 0)
#1 C:\laragon\www\api.denver\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\laragon\www\api.denver\system\Database\BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\laragon\www\api.denver\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\laragon\www\api.denver\system\Model.php(250): CodeIgniter\Database\BaseBuilder->get()
#5 C:\laragon\www\api.denver\system\BaseModel.php(623): CodeIgniter\Model->doFirst()
#6 C:\laragon\www\api.denver\app\Models\PadreModel.php(22): CodeIgniter\BaseModel->first()
#7 C:\laragon\www\api.denver\app\Controllers\Padre.php(114): App\Models\PadreModel->login('jose@gmail.com', 'jose')
#8 C:\laragon\www\api.denver\system\CodeIgniter.php(927): App\Controllers\Padre->login()
#9 C:\laragon\www\api.denver\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Padre))
#10 C:\laragon\www\api.denver\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\laragon\www\api.denver\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'2806:1016:8:8668:11ab:998c:8333:4214' (using password: YES) in C:\laragon\www\api.denver\system\Database\MySQLi\Connection.php:215
Stack trace:
#0 C:\laragon\www\api.denver\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\laragon\www\api.denver\system\Database\BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\laragon\www\api.denver\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\laragon\www\api.denver\system\Model.php(250): CodeIgniter\Database\BaseBuilder->get()
#4 C:\laragon\www\api.denver\system\BaseModel.php(623): CodeIgniter\Model->doFirst()
#5 C:\laragon\www\api.denver\app\Models\PadreModel.php(22): CodeIgniter\BaseModel->first()
#6 C:\laragon\www\api.denver\app\Controllers\Padre.php(114): App\Models\PadreModel->login('jose@gmail.com', 'jose')
#7 C:\laragon\www\api.denver\system\CodeIgniter.php(927): App\Controllers\Padre->login()
#8 C:\laragon\www\api.denver\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Padre))
#9 C:\laragon\www\api.denver\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\laragon\www\api.denver\public\index.php(67): CodeIgniter\CodeIgniter->run()
#11 {main}
CRITICAL - 2022-11-10 13:23:16 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'2806:1016:8:8668:11ab:998c:8333:4214' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 418.
 1 SYSTEMPATH\Database\BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `padres`
WHERE `correo` = :correo:
AND `pass` = :pass:
 LIMIT 1', [...], false)
 3 SYSTEMPATH\Model.php(250): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(623): CodeIgniter\Model->doFirst()
 5 APPPATH\Models\PadreModel.php(22): CodeIgniter\BaseModel->first()
 6 APPPATH\Controllers\Padre.php(114): App\Models\PadreModel->login('jose@gmail.com', 'jose')
 7 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\Padre->login()
 8 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Padre))
 9 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2022-11-10 13:23:17 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'u534750869_spoonme'@'2806:1016:8:8668:11ab:998c:8333:4214' (using password: YES) in C:\laragon\www\api.denver\system\Database\MySQLi\Connection.php:171
Stack trace:
#0 C:\laragon\www\api.denver\system\Database\MySQLi\Connection.php(171): mysqli->real_connect('denvermx.online', 'u534750869_spoo...', 'Jesus876', 'u534750869_denv...', 3306, '', 0)
#1 C:\laragon\www\api.denver\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\laragon\www\api.denver\system\Database\BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\laragon\www\api.denver\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\laragon\www\api.denver\system\Model.php(250): CodeIgniter\Database\BaseBuilder->get()
#5 C:\laragon\www\api.denver\system\BaseModel.php(623): CodeIgniter\Model->doFirst()
#6 C:\laragon\www\api.denver\app\Models\PadreModel.php(22): CodeIgniter\BaseModel->first()
#7 C:\laragon\www\api.denver\app\Controllers\Padre.php(114): App\Models\PadreModel->login('jose@gmail.com', 'jose')
#8 C:\laragon\www\api.denver\system\CodeIgniter.php(927): App\Controllers\Padre->login()
#9 C:\laragon\www\api.denver\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Padre))
#10 C:\laragon\www\api.denver\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\laragon\www\api.denver\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'2806:1016:8:8668:11ab:998c:8333:4214' (using password: YES) in C:\laragon\www\api.denver\system\Database\MySQLi\Connection.php:215
Stack trace:
#0 C:\laragon\www\api.denver\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\laragon\www\api.denver\system\Database\BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\laragon\www\api.denver\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\laragon\www\api.denver\system\Model.php(250): CodeIgniter\Database\BaseBuilder->get()
#4 C:\laragon\www\api.denver\system\BaseModel.php(623): CodeIgniter\Model->doFirst()
#5 C:\laragon\www\api.denver\app\Models\PadreModel.php(22): CodeIgniter\BaseModel->first()
#6 C:\laragon\www\api.denver\app\Controllers\Padre.php(114): App\Models\PadreModel->login('jose@gmail.com', 'jose')
#7 C:\laragon\www\api.denver\system\CodeIgniter.php(927): App\Controllers\Padre->login()
#8 C:\laragon\www\api.denver\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Padre))
#9 C:\laragon\www\api.denver\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\laragon\www\api.denver\public\index.php(67): CodeIgniter\CodeIgniter->run()
#11 {main}
CRITICAL - 2022-11-10 13:23:17 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'2806:1016:8:8668:11ab:998c:8333:4214' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 418.
 1 SYSTEMPATH\Database\BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `padres`
WHERE `correo` = :correo:
AND `pass` = :pass:
 LIMIT 1', [...], false)
 3 SYSTEMPATH\Model.php(250): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(623): CodeIgniter\Model->doFirst()
 5 APPPATH\Models\PadreModel.php(22): CodeIgniter\BaseModel->first()
 6 APPPATH\Controllers\Padre.php(114): App\Models\PadreModel->login('jose@gmail.com', 'jose')
 7 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\Padre->login()
 8 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Padre))
 9 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
